/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Operaciones;
import java.awt.BorderLayout;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Equipos;
import modelo.Partidas;
import org.hibernate.Query;

/**
 *
 * @author Julia
 */
public class JuegoIndividual extends javax.swing.JPanel {

    /**
     * Creates new form JuegoIndividual
     */
    Operaciones oper;
    private ArrayList<JButton> buttons = new ArrayList<JButton>();
    private ArrayList<JLabel> labels = new ArrayList<JLabel>();
    private int num_ronda;
    private Partidas partida;
    private boolean finJuego=false;
    public JuegoIndividual(Partidas partida) {
        initComponents();
        
        num_ronda=1;
        
        oper=new Operaciones();
        buttons.add(agregar_ronda1);
        buttons.add(agregar_ronda2);
        buttons.add(agregar_ronda3);
        buttons.add(agregar_ronda4);
        
        labels.add(nombre_jugador1);
        labels.add(nombre_jugador2);
        labels.add(nombre_jugador3);
        labels.add(nombre_jugador4);
        
        maximo.setText(partida.getMaximopunto().toString());
        System.out.println("----");
        this.partida=partida;
        int i=0;
        for(Equipos e:partida.getEquiposes()){
            labels.get(i).setText(e.getNombre());
           i++;
        }
    }
    private Equipos buscarEquipo(int index){
        int i=0;
        for(Equipos e:partida.getEquiposes()){
            if(index==i){
            return e;
            }
            i++;
        }
        return null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        container = new javax.swing.JPanel();
        nombre_jugador1 = new javax.swing.JLabel();
        agregar_ronda3 = new javax.swing.JButton();
        nombre_jugador2 = new javax.swing.JLabel();
        agregar_ronda1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        agregar_ronda4 = new javax.swing.JButton();
        agregar_ronda2 = new javax.swing.JButton();
        nombre_jugador3 = new javax.swing.JLabel();
        maximo = new javax.swing.JLabel();
        nombre_jugador4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablero = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        container.setBackground(new java.awt.Color(255, 255, 255));

        nombre_jugador1.setText("Jugador1");

        agregar_ronda3.setText("+");
        agregar_ronda3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_ronda3ActionPerformed(evt);
                agregar_ronda(evt);
            }
        });

        nombre_jugador2.setText("Jugador2");

        agregar_ronda1.setText("+");
        agregar_ronda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_ronda(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Máximo:");

        agregar_ronda4.setText("+");
        agregar_ronda4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_ronda4ActionPerformed(evt);
                agregar_ronda(evt);
            }
        });

        agregar_ronda2.setText("+");
        agregar_ronda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_ronda2ActionPerformed(evt);
                agregar_ronda(evt);
            }
        });

        nombre_jugador3.setText("Jugador3");

        maximo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        maximo.setText("100");

        nombre_jugador4.setText("Jugador4");

        tablero.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tablero.setTableHeader(null);
        jScrollPane2.setViewportView(tablero);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("#");

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(containerLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombre_jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(agregar_ronda1))
                                .addGap(18, 18, 18)
                                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombre_jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(agregar_ronda2))
                                .addGap(18, 18, 18)
                                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombre_jugador3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(agregar_ronda3))
                                .addGap(18, 18, 18)
                                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(agregar_ronda4)
                                    .addComponent(nombre_jugador4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11))))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maximo)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(maximo))
                .addGap(18, 18, 18)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre_jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre_jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre_jugador3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre_jugador4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar_ronda2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregar_ronda1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregar_ronda4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregar_ronda3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agregar_ronda3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_ronda3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregar_ronda3ActionPerformed

    private void agregar_ronda4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_ronda4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregar_ronda4ActionPerformed

    private void agregar_ronda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_ronda2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregar_ronda2ActionPerformed

    private void agregar_ronda(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_ronda
        if(!finJuego){
        
        String puntos = JOptionPane.showInputDialog(
                this,
                "Puntos",
                "Crear ronda",
                JOptionPane.INFORMATION_MESSAGE
        );
        //try{
            Integer.parseInt(puntos);
            int index=buttons.indexOf((JButton)evt.getSource());
            System.out.println(index);
                if(index!=-1){
                    Equipos e=buscarEquipo(index);
                    System.out.println(e.getNombre());
                    oper.agregarRonda(this.partida,e,Integer.parseInt(puntos),num_ronda);
                    DefaultTableModel model = (DefaultTableModel) tablero.getModel();
                    String row[]=new String[]{Integer.toString(num_ronda), "", "", "", ""};
                    row[index+1]=puntos;
                    
                    model.addRow(anexarPuntosTotales(row,e.getId()));
                    num_ronda++;
                }
        //}catch(Exception e){
        //    JOptionPane.showMessageDialog(null, "Los puntos no son un número válido");    
        //}
        }
    }//GEN-LAST:event_agregar_ronda
    private String[] anexarPuntosTotales(String[] array, BigDecimal equipo_id){
        List<Object[]> result=oper.totalEnPartida(partida.getId(),equipo_id);
        int i=0;
        for(Equipos e:partida.getEquiposes()){
            boolean band=false;
            for(Object[] row:result){
                System.out.println(row[0]+" "+row[1]);
                System.out.println(e.getId());
                if(e.getId().toString().equals(row[0].toString())){
                    band=true;
                    if((Integer.parseInt(row[1].toString()))>Integer.parseInt(partida.getMaximopunto().toString())){
                        JOptionPane.showMessageDialog(null, "Ha ganado el jugador/equipo: "+e.getNombre());
                        finJuego=true;
                    }
                    array[i+1]+="/"+row[1];
                }
            }
            i++;
        }
        return array;
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar_ronda1;
    private javax.swing.JButton agregar_ronda2;
    private javax.swing.JButton agregar_ronda3;
    private javax.swing.JButton agregar_ronda4;
    private javax.swing.JPanel container;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel maximo;
    private javax.swing.JLabel nombre_jugador1;
    private javax.swing.JLabel nombre_jugador2;
    private javax.swing.JLabel nombre_jugador3;
    private javax.swing.JLabel nombre_jugador4;
    private javax.swing.JTable tablero;
    // End of variables declaration//GEN-END:variables
}
