/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Operaciones;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import modelo.Jugadores;

/**
 *
 * @author loreanaisabel
 */
public class PartidasGanadasCero extends javax.swing.JPanel {

    /**
     * Creates new form PartidasGanadasCero
     */
    protected List<Object[]> jugadoresGanadores;
    protected List<Object[]> jugadoresCero;
    protected DefaultTableModel modeloGanar; 
    protected DefaultTableModel modeloCero; 
    
    protected Operaciones oper;
    
    public PartidasGanadasCero() {
        initComponents();
        oper = new Operaciones();
        
        jugadoresGanadores = oper.PartidasGanadas();
        jugadoresCero = oper.PartidasEnCero();
        modeloGanar=(DefaultTableModel) TablaGanar.getModel(); 
        modeloCero=(DefaultTableModel) TablaCero.getModel();
        
        for (Object[] datos : jugadoresGanadores) {
            modeloGanar.addRow(datos);
        }
        TablaGanar.setModel(modeloGanar);
        
        for (Object[] datos : jugadoresCero) {
            modeloCero.addRow(datos);
        }
        TablaCero.setModel(modeloCero);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ganadores = new java.awt.Label();
        label1 = new java.awt.Label();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaGanar = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCero = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        Ganadores.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        Ganadores.setText("Cantidad de Partidas Ganadas");

        label1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        label1.setText("Cantidad de Partidas  en 0");

        TablaGanar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Juagador", "Cantidad de Partidas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaGanar.setRowHeight(20);
        jScrollPane3.setViewportView(TablaGanar);

        TablaCero.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jugador", "Cantidad de Partidas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaCero.setRowHeight(20);
        jScrollPane1.setViewportView(TablaCero);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ganadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Ganadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(225, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label Ganadores;
    private javax.swing.JTable TablaCero;
    private javax.swing.JTable TablaGanar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
