package modelo;
// Generated Feb 24, 2018 10:50:50 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Equipos generated by hbm2java
 */
public class Equipos  implements java.io.Serializable {


     private BigDecimal id;
     private Jugadores jugadoresByJugadoresId;
     private Jugadores jugadoresByJugadoresId1;
     private String nombre;
     private Set partidases = new HashSet(0);
     private Set rondases = new HashSet(0);
     private Set partidosEquiposes = new HashSet(0);

    public Equipos() {
    }
    public Equipos(Jugadores jugadoresByJugadoresId) {
        this.jugadoresByJugadoresId = jugadoresByJugadoresId;
    }
	
    public Equipos(BigDecimal id, Jugadores jugadoresByJugadoresId) {
        this.id = id;
        this.jugadoresByJugadoresId = jugadoresByJugadoresId;
    }
    public Equipos(BigDecimal id, Jugadores jugadoresByJugadoresId, Jugadores jugadoresByJugadoresId1, String nombre, Set partidases, Set rondases, Set partidosEquiposes) {
       this.id = id;
       this.jugadoresByJugadoresId = jugadoresByJugadoresId;
       this.jugadoresByJugadoresId1 = jugadoresByJugadoresId1;
       this.nombre = nombre;
       this.partidases = partidases;
       this.rondases = rondases;
       this.partidosEquiposes = partidosEquiposes;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Jugadores getJugadoresByJugadoresId() {
        return this.jugadoresByJugadoresId;
    }
    
    public void setJugadoresByJugadoresId(Jugadores jugadoresByJugadoresId) {
        this.jugadoresByJugadoresId = jugadoresByJugadoresId;
    }
    public Jugadores getJugadoresByJugadoresId1() {
        return this.jugadoresByJugadoresId1;
    }
    
    public void setJugadoresByJugadoresId1(Jugadores jugadoresByJugadoresId1) {
        this.jugadoresByJugadoresId1 = jugadoresByJugadoresId1;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getPartidases() {
        return this.partidases;
    }
    
    public void setPartidases(Set partidases) {
        this.partidases = partidases;
    }
    public Set getRondases() {
        return this.rondases;
    }
    
    public void setRondases(Set rondases) {
        this.rondases = rondases;
    }
    public Set getPartidosEquiposes() {
        return this.partidosEquiposes;
    }
    
    public void setPartidosEquiposes(Set partidosEquiposes) {
        this.partidosEquiposes = partidosEquiposes;
    }




}


