package modelo;
// Generated Feb 24, 2018 10:50:50 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;

/**
 * Equipos generated by hbm2java
 */
public class Equipos  implements java.io.Serializable {


     private BigDecimal id;
     private Jugadores jugadoresByJugadoresId;
     private Jugadores jugadoresByJugadoresId1;
     private String nombre;
     private Set<Rondas> rondases = new HashSet<Rondas>(0);
     private Set<Partidas> partidases = new HashSet<Partidas>(0);
     private Set partidosEquiposes = new HashSet(0);

    public Set getPartidosEquiposes() {
        return partidosEquiposes;
    }

    public void setPartidosEquiposes(Set partidosEquiposes) {
        this.partidosEquiposes = partidosEquiposes;
    }

    public Set<Rondas> getRondases() {
        return rondases;
    }

    public void setRondases(Set<Rondas> rondases) {
        this.rondases = rondases;
    }


    public Equipos() {
    }
    public Equipos(Jugadores jugadoresByJugadoresId) {
        this.nombre=jugadoresByJugadoresId.getNombre();
        this.jugadoresByJugadoresId = jugadoresByJugadoresId;
    }
    public Equipos(String nombre, ArrayList<Jugadores> jugador) {
        this.nombre = nombre;
        System.out.println("const "+nombre);
            if(nombre.isEmpty()){
                System.out.println("Empty");
                this.nombre=jugador.get(0).getNombre()+"_"+jugador.get(1).getNombre();
            }
        this.jugadoresByJugadoresId = jugador.get(0);
        this.jugadoresByJugadoresId1 = jugador.get(1);
    }
    
    public Equipos(BigDecimal id, Jugadores jugadoresByJugadoresId) {
        this.id = id;
        this.jugadoresByJugadoresId = jugadoresByJugadoresId;
    }
    public Equipos(BigDecimal id, Jugadores jugadoresByJugadoresId, Jugadores jugadoresByJugadoresId1, String nombre, Set partidases, Set rondases, Set partidosEquiposes) {
       this.id = id;
       this.jugadoresByJugadoresId = jugadoresByJugadoresId;
       this.jugadoresByJugadoresId1 = jugadoresByJugadoresId1;
       this.nombre = nombre;
        System.out.println("Nombre del equipo "+nombre);
            if(nombre==null || nombre.isEmpty()){
                this.nombre=jugadoresByJugadoresId.getNombre()+"_"+jugadoresByJugadoresId1.getNombre();
            }
       this.partidases = partidases;
       this.rondases = rondases;
       //this.partidosEquiposes = partidosEquiposes;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Jugadores getJugadoresByJugadoresId() {
        return this.jugadoresByJugadoresId;
    }
    
    public void setJugadoresByJugadoresId(Jugadores jugadoresByJugadoresId) {
        this.jugadoresByJugadoresId = jugadoresByJugadoresId;
    }
    public Jugadores getJugadoresByJugadoresId1() {
        return this.jugadoresByJugadoresId1;
    }
    
    public void setJugadoresByJugadoresId1(Jugadores jugadoresByJugadoresId1) {
        this.jugadoresByJugadoresId1 = jugadoresByJugadoresId1;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Set<Partidas> getPartidases() {
        return partidases;
    }

    public void setPartidases(Set<Partidas> partidases) {
        this.partidases = partidases;
    }


}


