package modelo;
// Generated Feb 24, 2018 10:50:50 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Jugadores generated by hbm2java
 */
public class Jugadores  implements java.io.Serializable {


     private BigDecimal id;
     private String nombre;
     private Set equiposesForJugadoresId = new HashSet(0);
     private Set equiposesForJugadoresId1 = new HashSet(0);

    public Jugadores() {
    }

	
    public Jugadores(BigDecimal id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public Jugadores(BigDecimal id, String nombre, Set equiposesForJugadoresId, Set equiposesForJugadoresId1) {
       this.id = id;
       this.nombre = nombre;
       this.equiposesForJugadoresId = equiposesForJugadoresId;
       this.equiposesForJugadoresId1 = equiposesForJugadoresId1;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getEquiposesForJugadoresId() {
        return this.equiposesForJugadoresId;
    }
    
    public void setEquiposesForJugadoresId(Set equiposesForJugadoresId) {
        this.equiposesForJugadoresId = equiposesForJugadoresId;
    }
    public Set getEquiposesForJugadoresId1() {
        return this.equiposesForJugadoresId1;
    }
    
    public void setEquiposesForJugadoresId1(Set equiposesForJugadoresId1) {
        this.equiposesForJugadoresId1 = equiposesForJugadoresId1;
    }




}


