package modelo;
// Generated Feb 24, 2018 10:50:50 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Partidas generated by hbm2java
 */
public class Partidas  implements java.io.Serializable {


     private BigDecimal id;
     private Equipos equipos;
     private Date fecha;
     private BigDecimal maximopunto;
     private Set rondases = new HashSet(0);
     private Set partidosEquiposes = new HashSet(0);

    public Partidas() {
    }

	
    public Partidas(Date fecha, BigDecimal maximopunto) {
        this.fecha = fecha;
        this.maximopunto = maximopunto;
    }
    public Partidas(BigDecimal id, Equipos equipos, Date fecha, BigDecimal maximopunto, Set rondases, Set partidosEquiposes) {
       this.id = id;
       this.equipos = equipos;
       this.fecha = fecha;
       this.maximopunto = maximopunto;
       this.rondases = rondases;
       this.partidosEquiposes = partidosEquiposes;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Equipos getEquipos() {
        return this.equipos;
    }
    
    public void setEquipos(Equipos equipos) {
        this.equipos = equipos;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public BigDecimal getMaximopunto() {
        return this.maximopunto;
    }
    
    public void setMaximopunto(BigDecimal maximopunto) {
        this.maximopunto = maximopunto;
    }
    public Set getRondases() {
        return this.rondases;
    }
    
    public void setRondases(Set rondases) {
        this.rondases = rondases;
    }
    public Set getPartidosEquiposes() {
        return this.partidosEquiposes;
    }
    
    public void setPartidosEquiposes(Set partidosEquiposes) {
        this.partidosEquiposes = partidosEquiposes;
    }




}


