package modelo;
// Generated Feb 24, 2018 10:50:50 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Rondas generated by hbm2java
 */
public class Rondas  implements java.io.Serializable {


     private BigDecimal id;
     private Partidas partidas;
     private Equipos equipos;
     private BigDecimal numeroronda;
     private BigDecimal puntos;

    public Rondas() {
    }

    public Rondas(Partidas partidas, Equipos equipos, BigDecimal numeroronda, BigDecimal puntos) {
       this.partidas = partidas;
       this.equipos = equipos;
       this.numeroronda = numeroronda;
       this.puntos = puntos;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Partidas getPartidas() {
        return this.partidas;
    }
    
    public void setPartidas(Partidas partidas) {
        this.partidas = partidas;
    }
    public Equipos getEquipos() {
        return this.equipos;
    }
    
    public void setEquipos(Equipos equipos) {
        this.equipos = equipos;
    }
    public BigDecimal getNumeroronda() {
        return this.numeroronda;
    }
    
    public void setNumeroronda(BigDecimal numeroronda) {
        this.numeroronda = numeroronda;
    }
    public BigDecimal getPuntos() {
        return this.puntos;
    }
    
    public void setPuntos(BigDecimal puntos) {
        this.puntos = puntos;
    }




}


